
all:
	cd arduino-code && make shlib
#	cd i2c-code
	cd sim-code && make prog

clean:
	cd arduino-code && make clean
#	cd i2c-code
	cd sim-code && make clean

check:
	cd arduino-code && make shlib
#	cd i2c-code
	cd sim-code && make check 
