.TH Jearduino 1
.SH NAME
Jearduino \- a graphical frontend to Searduino's simulator
.SH SYNOPSIS
searduino-jearduino.sh [OPTIONS]
.SH DESCRIPTION
Graphical frontend that simulates an Arduino board and runs Arduino code in it.
.SH OPTIONS
.TP
.B --board <board>
 Set Arduino board to use
.TP
.B --arduino-code <file>
 Set file (shared object) to execute
.TP
.B --searduino-project <dir>
 Loads Searduio project as found in dir
.TP
.B --build
 Build project after loading it
.TP
.B --start
 Start project after loading it
.TP
.B --help
 Prints this message
.TP
.B 
 
.TP
