#
#       Searduino
#                                                                   
# Basically a couple of Makefile wrapping the Ardunio
# C and C++ files
#                                                                   
#  Copyright (C) 2011, 2012 Henrik Sandklef      
#                                                                   
# This program is free software; you can redistribute it and/or     
# modify it under the terms of the GNU General Public License       
# as published by the Free Software Foundation; either version 3    
# of the License, or any later version.                             
#                                                                   
#                                                                   
# This program is distributed in the hope that it will be useful,   
# but WITHOUT ANY WARRANTY; without even the implied warranty of    
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the     
# GNU General Public License for more details.                      
#                                                                   
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software       
# Foundation, Inc., 51 Franklin Street, Boston,            
# MA  02110-1301, USA.                                              
#
#

all: uno mega due mega2560
	cd libraries && make all

uno:
	make -f Makefile.uno

due:
	make -f Makefile.due

mega:
	make -f Makefile.mega

mega2560:
	make -f Makefile.mega2560

clean:
	make -f Makefile.uno clean
	cd libraries && make clean

check:
	@echo "Nothing to do in arduino-sources"

install: due uno mega mega2560
	 @echo "installing to __INSTALL_DIR__"
	 mkdir -p  __INSTALL_DIR__/libs/searduino/arduino-libs 
	 @cp -r libs/*     __INSTALL_DIR__/libs/searduino/arduino-libs/

	 @mkdir -p         __INSTALL_DIR__/include/searduino/arduino-sources/core
	 @mkdir -p         __INSTALL_DIR__/include/searduino/arduino-sources/variants
	 @mkdir -p         __INSTALL_DIR__/share/examples/arduino

	 @cp -r core/*.h   __INSTALL_DIR__/include/searduino/arduino-sources/core/
	 @cp -r variants/* __INSTALL_DIR__/include/searduino/arduino-sources/variants/
#
# This is an ugly hack to get around the problem of 99 chars max length in tar
#	 
	 @cp -r ../ard-ex/*  __INSTALL_DIR__/share/examples/arduino/

	cd libraries && make install


distdir:
	echo dummy impl
